---
deployment:
  tasks:
    - export REPOPATH=/home/weddingbes/repositories/invitation/*
    - export SITEPATH=/home/weddingbes/public_html/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH